### ISSUE TITLE
Passing through walls!

### ISSUE THREAD

**Issue by romangarms** [eden-annora/TheNautilus#35]
**What's the bug?**
In some instances you can go directly through walls

**What causes the bug?**
Store momentum, go towards diagonal wall at angle, and use momentum ability as you are about to go through

**How should be the bug be fixed?**
-Should walls be thicker?
-Momentum ability disabled when facing a wall?
-Reduce speed if about to hit wall?

**Screenshots**
![image](https://github.com/eden-annora/TheNautilus/assets/38168462/6c62e2e8-39c5-4e74-a72e-46803605fe94)

**Comment by eden-annora** [comment]
fixed!
5x the bump distance is now applied when collision occurs

**Comment by eden-annora** [comment]
also fixed the speed caps to be circular instead of capping the values individually
